repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff          # linter — corrige ce qu'il peut, bloque sinon
        args: [--fix]
      - id: ruff-format   # formatter (remplace black)

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.408
    hooks:
      - id: pyright
